language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
script:
  - mvn -q test
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
